// <auto-generated />
using System;
using AeroAdapter.Infrastructure.Persistences;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AeroAdapter.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AeroAdapter.Infrastructure.Persistences.Entities.CreateChannel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<short>("baudrate")
                        .HasColumnType("smallint");

                    b.Property<short>("c_model_id")
                        .HasColumnType("smallint");

                    b.Property<short>("c_port")
                        .HasColumnType("smallint");

                    b.Property<short>("c_rts_mode")
                        .HasColumnType("smallint");

                    b.Property<short>("c_type")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("n_channel_id")
                        .HasColumnType("smallint");

                    b.Property<short>("timer_1")
                        .HasColumnType("smallint");

                    b.Property<short>("timer_2")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("CreateChannels");

                    b.HasData(
                        new
                        {
                            id = 1,
                            baudrate = (short)0,
                            c_model_id = (short)0,
                            c_port = (short)0,
                            c_rts_mode = (short)0,
                            c_type = (short)7,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            n_channel_id = (short)1,
                            timer_1 = (short)3000,
                            timer_2 = (short)0,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AeroAdapter.Infrastructure.Persistences.Entities.SystemLevelSpecification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<short>("b_direct_mode")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("debug_rq")
                        .HasColumnType("smallint");

                    b.Property<short>("n_debug_arg")
                        .HasColumnType("smallint");

                    b.Property<short>("n_holidays")
                        .HasColumnType("smallint");

                    b.Property<short>("n_ports")
                        .HasColumnType("smallint");

                    b.Property<short>("n_scps")
                        .HasColumnType("smallint");

                    b.Property<short>("n_timezones")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("SystemLevelSpecifications");

                    b.HasData(
                        new
                        {
                            id = 1,
                            b_direct_mode = (short)1,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            debug_rq = (short)0,
                            n_debug_arg = (short)0,
                            n_holidays = (short)0,
                            n_ports = (short)1024,
                            n_scps = (short)1024,
                            n_timezones = (short)0,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
